services:
  app:
    build: .
    container_name: todo_list_app
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todo_list
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
    command: >
      sh -c "until nc -z db 3306; do echo 'Waiting for MySQL...'; sleep 2; done;
      php artisan migrate --force;
      php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: todo_list_db
    environment:
      MYSQL_DATABASE: todo_list
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
